name: Manual run

on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm test

      - name: Test action with TRX sample
        uses: ./
        if: success() || failure()
        with:
          name: Sample TRX Report
          path: __tests__/fixtures/dotnet-trx.trx
